version: "3.9"
services:
  mongodb:
    image: mongo:4.4.6
    container_name: mongo
    networks:
      - compose-bridge

  books:
    image: dockeridjoseromario/books:1.0
    container_name: app-node-book
    networks:
      - compose-bridge
    ports:
      - 3000:3000
    depends_on:
      - mongodb
networks:
  compose-bridge:
    driver: bridge  
